FROM bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8

ENV HIVE_VERSION 3.1.0

ENV HIVE_HOME /opt/hive
ENV PATH $HIVE_HOME/bin:$PATH
ENV HADOOP_HOME /opt/hadoop-$HADOOP_VERSION


WORKDIR /opt


RUN  apt-get update && apt-get install -y wget procps && \
    wget https://archive.apache.org/dist/hive/hive-$HIVE_VERSION/apache-hive-$HIVE_VERSION-bin.tar.gz && \
    tar -xzvf apache-hive-$HIVE_VERSION-bin.tar.gz && \
    mv apache-hive-$HIVE_VERSION-bin hive 
RUN rm $HIVE_HOME/lib/guava-19.0.jar 
COPY guava-27.0-jre.jar $HIVE_HOME/lib/ 
COPY postgresql-42.5.0.jar /usr/share/java/postgresql-jdbc.jar
COPY postgresql-42.5.0.jar $HIVE_HOME/lib/postgresql-jdbc.jar
RUN rm $HIVE_HOME/lib/postgresql-9.4.1208.jre7.jar
ADD conf/hive-site.xml $HIVE_HOME/conf
RUN chmod 644 /usr/share/java/postgresql-jdbc.jar
RUN chmod 644 $HIVE_HOME/lib/postgresql-jdbc.jar
# RUN ${HIVE_HOME}/bin/schematool -dbType postgres -initSchema
ADD conf/hive-site.xml $HIVE_HOME/conf
ADD conf/beeline-log4j2.properties $HIVE_HOME/conf
ADD conf/hive-env.sh $HIVE_HOME/conf
ADD conf/hive-exec-log4j2.properties $HIVE_HOME/conf
ADD conf/hive-log4j2.properties $HIVE_HOME/conf
ADD conf/ivysettings.xml $HIVE_HOME/conf
ADD conf/llap-daemon-log4j2.properties $HIVE_HOME/conf

COPY startup.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/startup.sh

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
RUN apt-get install -y curl
ENV HBASE_VERSION 2.5.3
ENV HBASE_URL https://archive.apache.org/dist/hbase/$HBASE_VERSION/hbase-$HBASE_VERSION-bin.tar.gz
RUN set -x \
    && wget "$HBASE_URL" \
    && tar -xvf hbase-${HBASE_VERSION}-bin.tar.gz  \
    && mv hbase-${HBASE_VERSION} /opt/hbase \
    && rm hbase-${HBASE_VERSION}-bin.tar.gz*
RUN rm apache-hive-$HIVE_VERSION-bin.tar.gz && \
    apt-get --purge remove -y wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN ln -s /opt/hbase/conf /etc/hbase
RUN mkdir /opt/hbase/logs


ENV HBASE_PREFIX=/opt/hbase
ENV HBASE_CONF_DIR=/etc/hbase

ENV USER=root
ENV PATH $HBASE_PREFIX/bin/:$PATH

RUN export HBASE_DISABLE_HADOOP_CLASSPATH_LOOKUP=true

ENTRYPOINT ["entrypoint.sh"]
CMD ["startup.sh"]